scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]

  - job_name: "weblogic"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          application: "DummyBankApp"
          environment: "development"
